language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

cache: pip
# command to install dependencies
install:
  - cat /proc/cpuinfo
  - free -m
  - pip install dask==2021.1.1 distributed==2021.1.1 dask-ml
  - pip install -r requirements.txt -r requirements-ft.txt
  - pip install -q pytest-cov==2.4.0 python-coveralls codacy-coverage
  - pip list
# command to run tests
script:
  - pytest --cov=hypernets --durations=30

notifications:
  recipients:
    - yangjian@zetyun.com
    - lixf@zetyun.com

  on_success: change
  on_failure: change

after_success:
  - coveralls
  - coverage xml
  - python-codacy-coverage -r coverage.xml
