# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from hypernets.dispatchers.cluster.grpc.proto import spec_pb2 as hypernets_dot_dispatchers_dot_cluster_dot_grpc_dot_proto_dot_spec__pb2


class SearchDriverStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ping = channel.unary_unary(
        '/hypernets.dispatchers.cluster.grpc.proto.SearchDriver/ping',
        request_serializer=hypernets_dot_dispatchers_dot_cluster_dot_grpc_dot_proto_dot_spec__pb2.PingMessage.SerializeToString,
        response_deserializer=hypernets_dot_dispatchers_dot_cluster_dot_grpc_dot_proto_dot_spec__pb2.PingMessage.FromString,
        )
    self.search = channel.stream_stream(
        '/hypernets.dispatchers.cluster.grpc.proto.SearchDriver/search',
        request_serializer=hypernets_dot_dispatchers_dot_cluster_dot_grpc_dot_proto_dot_spec__pb2.SearchRequest.SerializeToString,
        response_deserializer=hypernets_dot_dispatchers_dot_cluster_dot_grpc_dot_proto_dot_spec__pb2.SearchResponse.FromString,
        )


class SearchDriverServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ping(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def search(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SearchDriverServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ping': grpc.unary_unary_rpc_method_handler(
          servicer.ping,
          request_deserializer=hypernets_dot_dispatchers_dot_cluster_dot_grpc_dot_proto_dot_spec__pb2.PingMessage.FromString,
          response_serializer=hypernets_dot_dispatchers_dot_cluster_dot_grpc_dot_proto_dot_spec__pb2.PingMessage.SerializeToString,
      ),
      'search': grpc.stream_stream_rpc_method_handler(
          servicer.search,
          request_deserializer=hypernets_dot_dispatchers_dot_cluster_dot_grpc_dot_proto_dot_spec__pb2.SearchRequest.FromString,
          response_serializer=hypernets_dot_dispatchers_dot_cluster_dot_grpc_dot_proto_dot_spec__pb2.SearchResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'hypernets.dispatchers.cluster.grpc.proto.SearchDriver', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
