# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from hypernets.dispatchers.grpc.proto import predict_pb2 as hypernets_dot_dispatchers_dot_grpc_dot_proto_dot_predict__pb2


class PredictServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.predict = channel.unary_unary(
                '/hypernets.dispatchers.proto.PredictService/predict',
                request_serializer=hypernets_dot_dispatchers_dot_grpc_dot_proto_dot_predict__pb2.PredictRequest.SerializeToString,
                response_deserializer=hypernets_dot_dispatchers_dot_grpc_dot_proto_dot_predict__pb2.PredictResponse.FromString,
                )


class PredictServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def predict(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PredictServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'predict': grpc.unary_unary_rpc_method_handler(
                    servicer.predict,
                    request_deserializer=hypernets_dot_dispatchers_dot_grpc_dot_proto_dot_predict__pb2.PredictRequest.FromString,
                    response_serializer=hypernets_dot_dispatchers_dot_grpc_dot_proto_dot_predict__pb2.PredictResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hypernets.dispatchers.proto.PredictService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PredictService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hypernets.dispatchers.proto.PredictService/predict',
            hypernets_dot_dispatchers_dot_grpc_dot_proto_dot_predict__pb2.PredictRequest.SerializeToString,
            hypernets_dot_dispatchers_dot_grpc_dot_proto_dot_predict__pb2.PredictResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
