# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from hypernets.dispatchers.grpc.proto import spec_pb2 as hypernets_dot_dispatchers_dot_grpc_dot_proto_dot_spec__pb2


class SearchDriverStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ping = channel.unary_unary(
                '/hypernets.dispatchers.proto.SearchDriver/ping',
                request_serializer=hypernets_dot_dispatchers_dot_grpc_dot_proto_dot_spec__pb2.PingMessage.SerializeToString,
                response_deserializer=hypernets_dot_dispatchers_dot_grpc_dot_proto_dot_spec__pb2.PingMessage.FromString,
                )
        self.search = channel.stream_stream(
                '/hypernets.dispatchers.proto.SearchDriver/search',
                request_serializer=hypernets_dot_dispatchers_dot_grpc_dot_proto_dot_spec__pb2.SearchRequest.SerializeToString,
                response_deserializer=hypernets_dot_dispatchers_dot_grpc_dot_proto_dot_spec__pb2.SearchResponse.FromString,
                )


class SearchDriverServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def search(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SearchDriverServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ping': grpc.unary_unary_rpc_method_handler(
                    servicer.ping,
                    request_deserializer=hypernets_dot_dispatchers_dot_grpc_dot_proto_dot_spec__pb2.PingMessage.FromString,
                    response_serializer=hypernets_dot_dispatchers_dot_grpc_dot_proto_dot_spec__pb2.PingMessage.SerializeToString,
            ),
            'search': grpc.stream_stream_rpc_method_handler(
                    servicer.search,
                    request_deserializer=hypernets_dot_dispatchers_dot_grpc_dot_proto_dot_spec__pb2.SearchRequest.FromString,
                    response_serializer=hypernets_dot_dispatchers_dot_grpc_dot_proto_dot_spec__pb2.SearchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hypernets.dispatchers.proto.SearchDriver', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SearchDriver(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hypernets.dispatchers.proto.SearchDriver/ping',
            hypernets_dot_dispatchers_dot_grpc_dot_proto_dot_spec__pb2.PingMessage.SerializeToString,
            hypernets_dot_dispatchers_dot_grpc_dot_proto_dot_spec__pb2.PingMessage.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def search(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/hypernets.dispatchers.proto.SearchDriver/search',
            hypernets_dot_dispatchers_dot_grpc_dot_proto_dot_spec__pb2.SearchRequest.SerializeToString,
            hypernets_dot_dispatchers_dot_grpc_dot_proto_dot_spec__pb2.SearchResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
