# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from hypernets.dispatchers.grpc.proto import spec_pb2 as hypernets_dot_dispatchers_dot_grpc_dot_proto_dot_spec__pb2


class SearchDriverStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.next = channel.unary_unary(
                '/hypernets.dispatchers.proto.SearchDriver/next',
                request_serializer=hypernets_dot_dispatchers_dot_grpc_dot_proto_dot_spec__pb2.NextRequest.SerializeToString,
                response_deserializer=hypernets_dot_dispatchers_dot_grpc_dot_proto_dot_spec__pb2.TrailItem.FromString,
                )
        self.report = channel.unary_unary(
                '/hypernets.dispatchers.proto.SearchDriver/report',
                request_serializer=hypernets_dot_dispatchers_dot_grpc_dot_proto_dot_spec__pb2.TrailStatus.SerializeToString,
                response_deserializer=hypernets_dot_dispatchers_dot_grpc_dot_proto_dot_spec__pb2.RpcCode.FromString,
                )


class SearchDriverServicer(object):
    """Missing associated documentation comment in .proto file."""

    def next(self, request, context):
        """rpc fetch(DataRequest) returns (stream DataChunk) {}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def report(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SearchDriverServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'next': grpc.unary_unary_rpc_method_handler(
                    servicer.next,
                    request_deserializer=hypernets_dot_dispatchers_dot_grpc_dot_proto_dot_spec__pb2.NextRequest.FromString,
                    response_serializer=hypernets_dot_dispatchers_dot_grpc_dot_proto_dot_spec__pb2.TrailItem.SerializeToString,
            ),
            'report': grpc.unary_unary_rpc_method_handler(
                    servicer.report,
                    request_deserializer=hypernets_dot_dispatchers_dot_grpc_dot_proto_dot_spec__pb2.TrailStatus.FromString,
                    response_serializer=hypernets_dot_dispatchers_dot_grpc_dot_proto_dot_spec__pb2.RpcCode.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hypernets.dispatchers.proto.SearchDriver', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SearchDriver(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def next(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hypernets.dispatchers.proto.SearchDriver/next',
            hypernets_dot_dispatchers_dot_grpc_dot_proto_dot_spec__pb2.NextRequest.SerializeToString,
            hypernets_dot_dispatchers_dot_grpc_dot_proto_dot_spec__pb2.TrailItem.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def report(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hypernets.dispatchers.proto.SearchDriver/report',
            hypernets_dot_dispatchers_dot_grpc_dot_proto_dot_spec__pb2.TrailStatus.SerializeToString,
            hypernets_dot_dispatchers_dot_grpc_dot_proto_dot_spec__pb2.RpcCode.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
