# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python pytest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test_default:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        include:
          - os: macos-latest
            python-version: 3.8
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -q  "XlsxWriter<3.0.5" "dask<=2023.2.0" "distributed<=2023.2.0" -r requirements.txt -r requirements-zhcn.txt -r requirements-dask.txt -r requirements-extra.txt
        pip install -q pytest-cov==2.4.0  python-coveralls  codacy-coverage
        pip list
    - name: Test with pytest
      run: |
        pytest --cov=hypernets --durations=30


  test_with_dask_ft:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
#         os: [ubuntu-latest, windows-latest]
        os: [windows-latest, ubuntu-latest]
        python-version: [3.7, 3.8]
        ft-version: [0.27]
        woodwork-version: [0.13.0]
        dask-version: [2021.1.1, 2021.7.2]
        include:
          - os: ubuntu-20.04
            python-version: 3.6
            ft-version: 0.23
            woodwork-version: 0.1.0
            dask-version: 2021.1.1
          - os: ubuntu-latest
            python-version: 3.7
            ft-version: 1.2
            woodwork-version: 0.13.0
            dask-version: 2021.10.0
          - os: ubuntu-latest
            python-version: 3.8
            ft-version: 1.2
            woodwork-version: 0.13.0
            dask-version: 2021.10.0
          - os: windows-latest
            python-version: 3.8
            ft-version: 1.2
            woodwork-version: 0.13.0
            dask-version: 2021.10.0
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -q dask==${{ matrix.dask-version }} distributed==${{ matrix.dask-version }} dask-ml "featuretools==${{ matrix.ft-version }}" woodwork==${{ matrix.woodwork-version }} "pandas<1.5.0"
        pip install -q -r requirements.txt -r requirements-zhcn.txt -r requirements-extra.txt "scikit-learn<1.1.0" "XlsxWriter<3.0.5" "pyarrow<=4.0.0"
        pip install -q pytest-cov==2.4.0  python-coveralls  codacy-coverage
        pip list
    - name: Test with pytest
      run: |
        pytest --cov=hypernets --durations=30

  test_without_daskml:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: [3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -q -r requirements.txt "scikit-learn<1.1.0" "XlsxWriter<3.0.5"
        pip install -q pytest-cov==2.4.0  python-coveralls  codacy-coverage
        pip list
    - name: Test with pytest
      run: |
        pytest --cov=hypernets --durations=30


  test_without_geohash:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ]
        python-version: [3.7, 3.8]
        # dask-version: [2021.7.2,]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    # # pip install -q dask==${{ matrix.dask-version }} distributed==${{ matrix.dask-version }} dask-ml "pandas<1.5.0"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -q "dask<=2023.2.0" "distributed<=2023.2.0" dask-ml "pandas<1.5.0"
        pip install -q -r requirements.txt -r requirements-zhcn.txt "scikit-learn<1.1.0" "XlsxWriter<3.0.5"
        pip install -q pytest-cov==2.4.0  python-coveralls  codacy-coverage
        pip list
    - name: Test with pytest
      run: |
        pytest --cov=hypernets --durations=30
