# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python pytest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
#         os: [ubuntu-latest, windows-latest]
        os: [ubuntu-latest, windows-2022]
        python-version: [3.7, 3.8]
        ft-version: [0.27]
        dask-version: [2021.1.1, 2021.7.2]
        include:
          - os: ubuntu-latest
            python-version: 3.6
            ft-version: 0.23
            dask-version: 2021.1.1
          - os: ubuntu-latest
            python-version: 3.7
            ft-version: 1.2
            dask-version: 2021.10.0
          - os: ubuntu-latest
            python-version: 3.8
            ft-version: 1.2
            dask-version: 2021.10.0
          - os: windows-2022
            python-version: 3.8
            ft-version: 1.2
            dask-version: 2021.10.0
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -q dask==${{ matrix.dask-version }} distributed==${{ matrix.dask-version }} dask-ml "featuretools==${{ matrix.ft-version }}"
        pip install -q -r requirements.txt -r requirements-zhcn.txt
        pip install -q pytest-cov==2.4.0  python-coveralls  codacy-coverage
        pip list
    - name: Test with pytest
      run: |
        pytest --cov=hypernets --durations=30
